services:
  - type: web
    name: swis-analyse
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyCCnrruOeLHd5V4gKoDnhoKdXQThHqWKHs
      - key: PORT
        value: 8000
      - key: APP_ENV
        value: production